/*
 * This source file was generated by the Gradle 'init' task
 */
package org.test;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import com.lab.*;

class AccountTest {

    private Account account;
    private Account destAccount;

    @BeforeEach
    void setUp() {
        account = new Account(100.00);
        destAccount = new Account(50.00);
    }

    @Test
    void testSuspend() {
        account.suspend();
        assertFalse(account.isActive());
        assertEquals(Account.Status.SUSPENDED, account.getStatus());
    }

    @Test
    void testReactivate() {
        account.suspend();
        account.reactivate();
        assertTrue(account.isActive());
        assertEquals(Account.Status.ACTIVE, account.getStatus());
    }

    @Test
    void testIsActive() {
        assertTrue(account.isActive());
        account.suspend();
        assertFalse(account.isActive());
        account.close();
        assertFalse(account.isActive());
    }

    @Test
    void testTransferTo() {
        account.transferTo(destAccount, 50.00);
        assertEquals(50.00, account.getBalance());
        assertEquals(100.00, destAccount.getBalance());
    }

    @Test
    void testTransferToThrowsWhenSuspended() {
        account.suspend();
        var e = assertThrows(IllegalStateException.class, () -> account.transferTo(destAccount, 50.00));
        assertEquals("Account is unavailable.", e.getMessage());
    }

    @Test
    void testDepositThrowsWhenSuspended() {
        account.suspend();
        var e = assertThrows(IllegalStateException.class, () -> account.deposit(50.00));
        assertEquals("Account is unavailable.", e.getMessage());
    }

    @Test
    void testWithdrawThrowsWhenSuspended() {
        account.suspend();
        var e = assertThrows(IllegalStateException.class, () -> account.withdraw(50.00));
        assertEquals("Account is unavailable.", e.getMessage());
    }

    @Test
    void testFluentApiPattern() {
        account.deposit(100.00).withdraw(50.00).deposit(200.00);
        assertEquals(350.00, account.getBalance());
    }
}

class AccountManagerTest {

    private static AccountManager manager;

    @BeforeAll
    static void setUp() {
        manager = new AccountManager();
        manager.openAccount(100.00);
        manager.openAccount(200.00);
        manager.openAccount(300.00);
        manager.openAccount(400.00);
        manager.openAccount(500.00);

        manager.getAccount("1234-0002").close();
        manager.getAccount("1234-0004").suspend();
    }

    @Test
    void testListAccountsActive() {
        Account[] activeAccounts = manager.listAccounts(Account.Status.ACTIVE);
        assertEquals(3, activeAccounts.length);
        for (Account acc : activeAccounts) {
            assertEquals(Account.Status.ACTIVE, acc.getStatus());
        }
    }

    @Test
    void testListAccountsSuspended() {
        Account[] suspendedAccounts = manager.listAccounts(Account.Status.SUSPENDED);
        assertEquals(1, suspendedAccounts.length);
        assertEquals("1234-0004", suspendedAccounts[0].getAccountNumber());
    }

    @Test
    void testListAccountsClosed() {
        Account[] closedAccounts = manager.listAccounts(Account.Status.CLOSED);
        assertEquals(1, closedAccounts.length);
        assertEquals("1234-0002", closedAccounts[0].getAccountNumber());
    }

    @Test
    void testListAccountsDefault() {
        Account[] activeAccounts = manager.listAccounts();
        assertEquals(3, activeAccounts.length);
        for (Account acc : activeAccounts) {
            assertEquals(Account.Status.ACTIVE, acc.getStatus());
        }
    }
}

